language: python
python:
  - 3.6
addons:
  ssh_known_hosts:
  - github.com
  - heroku.com
cache: pip
install:
  - pip install -r web_api/requirements.txt
  - pip install -e web_api
script:
  - pytest web_api/
after_success:
  - openssl aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - git remote add heroku ssh://git@heroku.com/tmb-api.git
  - git subtree push --prefix web_api heroku master
