language: python
python:
  - 3.6
addons:
  ssh_known_hosts:
  - github.com
  - heroku.com
cache: pip
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libav-tools
install:
  - pip install -r web_api/requirements.txt
  - pip install -e web_api
script:
  - pytest web_api/ -W ignore::DeprecationWarning
after_success:
  - openssl aes-256-cbc -K $encrypted_6d39b13d5ccc_key -iv $encrypted_6d39b13d5ccc_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - git remote add heroku ssh://git@heroku.com/tmb-api.git
  - git subtree pull --squash --prefix web_api heroku master
  - git subtree push --prefix web_api heroku master
